# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a70a48b31fad93e1eeaebf63dc4223772e3030e3a952f5746768847815c447bdb804afc4d9b6cc78403ab90a9c66c7acbd3a057df65d05474cab80d5e83e5de

test:
  secret_key_base: 775d430f9a3e8899aa3c12912c916e4e2a2e6d9e3dcdf2eb6806f3464669a875992cc5e995a312fcdd4c8ca41578534f9d9dc40f250a3ee8f3098926dd5b1666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
